// Code generated by prismic-ts-codegen. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Author documents */
interface AuthorDocumentData {
    /**
     * Name field in *Author*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: author.name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    name: prismicT.TitleField;
    /**
     * Portrait field in *Author*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: author.portrait
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    portrait: prismicT.ImageField<never>;
    /**
     * Bio field in *Author*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: author.bio
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    bio: prismicT.RichTextField;
    /**
     * Book field in *Author*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: author.book
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    book: prismicT.RelationField<"book">;
    /**
     * Personal website field in *Author*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: author.personal_website
     * - **Tab**: Links
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    personal_website: prismicT.LinkField;
    /**
     * Facebook field in *Author*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: author.facebook
     * - **Tab**: Links
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    facebook: prismicT.LinkField;
    /**
     * Twitter field in *Author*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: author.twitter
     * - **Tab**: Links
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    twitter: prismicT.LinkField;
    /**
     * Instagram field in *Author*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: author.instagram
     * - **Tab**: Links
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    instagram: prismicT.LinkField;
    /**
     * Good Reads field in *Author*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: author.good_reads
     * - **Tab**: Links
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    good_reads: prismicT.LinkField;
    /**
     * Amazon field in *Author*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: author.amazon
     * - **Tab**: Links
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    amazon: prismicT.LinkField;
    /**
     * TikTok field in *Author*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: author.tiktok
     * - **Tab**: Links
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    tiktok: prismicT.LinkField;
    /**
     * Page title field in *Author*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: author.page_title
     * - **Tab**: Config
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    page_title: prismicT.KeyTextField;
    /**
     * SEO title field in *Author*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: author.seo_title
     * - **Tab**: Config
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    seo_title: prismicT.KeyTextField;
    /**
     * SEO description field in *Author*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: author.seo_description
     * - **Tab**: Config
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    seo_description: prismicT.KeyTextField;
    /**
     * Alternate Social Sharing Image field in *Author*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: author.alternate_social_sharing_image
     * - **Tab**: Config
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    alternate_social_sharing_image: prismicT.ImageField<never>;
}
/**
 * Author document from Prismic
 *
 * - **API ID**: `author`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AuthorDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<AuthorDocumentData>, "author", Lang>;
/** Content for Book documents */
interface BookDocumentData {
    /**
     * Title field in *Book*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: book.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * What it's retelling field in *Book*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: book.what_its_retelling
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    what_its_retelling: prismicT.RichTextField;
    /**
     * Author field in *Book*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: book.author
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    author: prismicT.RelationField<"author">;
    /**
     * Amazon link field in *Book*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: book.amazon_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    amazon_link: prismicT.LinkField;
    /**
     * Cover field in *Book*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: book.cover
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    cover: prismicT.ImageField<never>;
    /**
     * Synopsis field in *Book*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: book.synopsis
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    synopsis: prismicT.RichTextField;
    /**
     * Page title field in *Book*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: book.page_title
     * - **Tab**: Config
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    page_title: prismicT.KeyTextField;
    /**
     * SEO title field in *Book*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: book.seo_title
     * - **Tab**: Config
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    seo_title: prismicT.KeyTextField;
    /**
     * SEO description field in *Book*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: book.seo_description
     * - **Tab**: Config
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    seo_description: prismicT.KeyTextField;
    /**
     * Alternate Social Sharing Image field in *Book*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: book.alternate_social_sharing_image
     * - **Tab**: Config
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    alternate_social_sharing_image: prismicT.ImageField<never>;
}
/**
 * Book document from Prismic
 *
 * - **API ID**: `book`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BookDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<BookDocumentData>, "book", Lang>;
/** Content for Landing Page documents */
interface LandingPageDocumentData {
    /**
     * Hero heading field in *Landing Page*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: landing_page.hero_heading
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    hero_heading: prismicT.TitleField;
    /**
     * Hero subheading field in *Landing Page*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: landing_page.hero_subheading
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    hero_subheading: prismicT.TitleField;
    /**
     * About the series field in *Landing Page*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: landing_page.about_the_series
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    about_the_series: prismicT.RichTextField;
    /**
     * Slice Zone field in *Landing Page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: landing_page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<LandingPageDocumentDataSlicesSlice>;
    /**
     * Page title field in *Landing Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: landing_page.page_title
     * - **Tab**: Config
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    page_title: prismicT.KeyTextField;
    /**
     * SEO title field in *Landing Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: landing_page.seo_title
     * - **Tab**: Config
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    seo_title: prismicT.KeyTextField;
    /**
     * SEO description field in *Landing Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: landing_page.seo_description
     * - **Tab**: Config
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    seo_description: prismicT.KeyTextField;
    /**
     * Alternate social sharing image field in *Landing Page*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: landing_page.alternate_social_sharing_image
     * - **Tab**: Config
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    alternate_social_sharing_image: prismicT.ImageField<never>;
}
/**
 * Slice for *Landing Page → Slice Zone*
 *
 */
type LandingPageDocumentDataSlicesSlice = never;
/**
 * Landing Page document from Prismic
 *
 * - **API ID**: `landing_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingPageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<LandingPageDocumentData>, "landing_page", Lang>;
export type AllDocumentTypes = AuthorDocument | BookDocument | LandingPageDocument;
/**
 * Primary content in Hero → Primary
 *
 */
interface HeroSliceDefaultPrimary {
    /**
     * Title field in *Hero → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: hero.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *Hero → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: hero.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Hero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<HeroSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Hero*
 *
 */
type HeroSliceVariation = HeroSliceDefault;
/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: `Hero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSlice = prismicT.SharedSlice<"hero", HeroSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { AuthorDocumentData, AuthorDocument, BookDocumentData, BookDocument, LandingPageDocumentData, LandingPageDocumentDataSlicesSlice, LandingPageDocument, AllDocumentTypes, HeroSliceDefaultPrimary, HeroSliceDefault, HeroSliceVariation, HeroSlice };
    }
}
