// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Home Page documents */
interface HomePageDocumentData {
    /**
     * Name field in *Home Page*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: home_page.name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    name: prismicT.TitleField;
    /**
     * Bio field in *Home Page*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home_page.bio
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    bio: prismicT.RichTextField;
    /**
     * Page title field in *Home Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home_page.page_title
     * - **Tab**: Config
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    page_title: prismicT.KeyTextField;
    /**
     * SEO title field in *Home Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home_page.seo_title
     * - **Tab**: Config
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    seo_title: prismicT.KeyTextField;
    /**
     * SEO description field in *Home Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home_page.seo_description
     * - **Tab**: Config
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    seo_description: prismicT.KeyTextField;
    /**
     * Alternate social sharing image field in *Home Page*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: home_page.alternate_social_sharing_image
     * - **Tab**: Config
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    alternate_social_sharing_image: prismicT.ImageField<never>;
    /**
     * Facebook field in *Home Page*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: home_page.facebook
     * - **Tab**: External Links
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    facebook: prismicT.LinkField;
    /**
     * Twitter field in *Home Page*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: home_page.twitter
     * - **Tab**: External Links
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    twitter: prismicT.LinkField;
    /**
     * YouTube field in *Home Page*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: home_page.youtube
     * - **Tab**: External Links
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    youtube: prismicT.LinkField;
    /**
     * CodePen field in *Home Page*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: home_page.codepen
     * - **Tab**: External Links
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    codepen: prismicT.LinkField;
    /**
     * LinkedIn field in *Home Page*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: home_page.linkedin
     * - **Tab**: External Links
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    linkedin: prismicT.LinkField;
    /**
     * Instagram field in *Home Page*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: home_page.instagram
     * - **Tab**: External Links
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    instagram: prismicT.LinkField;
}
/**
 * Home Page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<HomePageDocumentData>, "home_page", Lang>;
export type AllDocumentTypes = HomePageDocument;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { HomePageDocumentData, HomePageDocument, AllDocumentTypes };
    }
}
